platform :ios, '12.0'
install! 'cocoapods',
    :deterministic_uuids => false
target 'plugg' do
  rn_path = '../node_modules/react-native'
  
  pod 'yoga', :path => "#{rn_path}/ReactCommon/yoga"
  pod 'React', :path => rn_path, :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNInAppBrowser', :path => '../node_modules/react-native-inappbrowser-reborn'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNAwesomeCardIO', :path => '../node_modules/react-native-awesome-card-io'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'
  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

  #TODO: Fix static linking for swift pods or add use_frameworks! to the top of file
  # pod 'lottie-ios', :path => '../node_modules/lottie-ios', :modular_headers => true
  # pod 'lottie-react-native', :path => '../node_modules/lottie-react-native', :modular_headers => true


  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
  react_project = Xcodeproj::Project.open("../node_modules/react-native/React/React.xcodeproj")
    react_project.main_group["React/Views"].files.each do |file|   
      if file.path.match(/^RCTWebView/) 
        file.remove_from_project
      end   
    end   
  react_project.save
end

