export const ADD_PAYMENT = "ADD_PAYMENT";
export const ADD_PAYMENT_SUCCESS = "ADD_PAYMENT_SUCCESS";
export const ADD_PAYMENT_FAIL = "ADD_PAYMENT_FAIL";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAIL = "DELETE_PAYMENT_FAIL";
export const CHANGE_DEFAULT_PAYMENT = "CHANGE_DEFAULT_PAYMENT";
export const CHANGE_DEFAULT_PAYMENT_SUCCESS = "CHANGE_DEFAULT_PAYMENT_SUCCESS";
export const CHANGE_DEFAULT_PAYMENT_FAIL = "CHANGE_DEFAULT_PAYMENT_FAIL";
export const GET_PAYMENT_METHODS = "GET_PAYMENT_METHODS";
export const GET_PAYMENT_METHODS_SUCCESS = "GET_PAYMENT_METHODS_SUCCESS";
export const GET_PAYMENT_METHODS_FAIL = "GET_PAYMENT_METHODS_FAIL";
export const CREATE_CUSTOMER_WITH_DEFAULT_CARD =
  "CREATE_CUSTOMER_WITH_DEFAULT_CARD";
export const CREATE_CUSTOMER_WITH_DEFAULT_CARD_SUCCESS =
  "CREATE_CUSTOMER_WITH_DEFAULT_CARD_SUCCESS";
export const CREATE_CUSTOMER_WITH_DEFAULT_CARD_FAIL =
  "CREATE_CUSTOMER_WITH_DEFAULT_CARD_FAIL";
export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAIL = "GET_CUSTOMER_FAIL";
